a=int(input("1st number"))
b=int(input("2 nd number"))
sum=(a+b)
difference=(a-b)
product=(a*b)
quotient=(a/b)
remainder=(a%b)
print(sum)
print(difference)
print(product)
print(quotient)
print(remainder)